<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnimeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('anime')->insert([
        	
        	[
        		'id' => 1,
                'judul' => 'ONE PIECE',
                'jumlah_episode' => '-',
                'rating' => '9.0',
                'rilis' => '1999',
                'sinopsis' => 'Gol D. Roger dikenal sebagai Raja Bajak laut,’ terkuat dan paling terkenal yang telah berlayar Grand Line.',
                'gambar' => 'LUFFY.jpeg',
                'status' => 'ONGOING',
                'studios' => 'TOEI ANIMATION',
                'duration' => '24 MIN / EPS',                
        		'id_abjad' => 1, 
                'id_genre' => 1, 
                'id_type' => 4,           	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],

        	[
        		'id' => 2,
                'judul' => 'DRAGON BALL',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 4, 
                'id_genre' => 1, 
                'id_type' => 4,               		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],
                 
            [
        		'id' => 3,
                'judul' => 'NARUTO SHIPPUDEN',
                'jumlah_episode' => '500',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 14, 
                'id_genre' => 1, 
                'id_type' => 'A',       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],

            [
        		'id' => 4,
                'judul' => 'BLEACH',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 2, 
                'id_genre' => 1, 
                'id_type' => 4,       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],                
                
            [
        		'id' => 5,
                'judul' => 'BOKU NO HERO ACADEMIA',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 2, 
                'id_genre' => 1, 
                'id_type' => 4,              		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 6,
                'judul' => 'SHINGEKI NO KYUJIN',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 19, 
                'id_genre' => 1, 
                'id_type' => 4,       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 7,
                'judul' => 'BORUTO: NARUTO NEXT GENERATIONS',
                'jumlah_episode' => '-',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 2, 
                'id_genre' => 2, 
                'id_type' => 4,              		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 8,
                'judul' => 'POKEMON',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 16, 
                'id_genre' => 2, 
                'id_type' => 4,              		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 9,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],     
            [
        		'id' => 10,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 11,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',              		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],       
            [
        		'id' => 12,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' =>13,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 14,
        		'nama_abjad' => 'N',     
        		'slug' =>'n',   		        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 15,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 16,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',            		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 17,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',        		        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 18,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',              		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 19,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       		        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 20,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       		        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 21,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       		        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],     
            [
        		'id' => 22,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       	        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],       
            [
        		'id' => 23,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',               		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 24,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       		        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 25,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',       		        		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
            [
        		'id' => 26,
                'judul' => '',
                'jumlah_episode' => '',
                'rating' => '',
                'rilis' => '',
                'sinopsis' => '',
                'gambar' => '',
                'status' => '',
                'studios' => '',
                'duration' => '',                
        		'id_abjad' => 'A', 
                'id_genre' => 'A', 
                'id_type' => 'A',               		
        		'created_at'      => \Carbon\Carbon::now(),
            	'updated_at'      => \Carbon\Carbon::now()
        	],      
        ]);
    
    }
}